apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep 
    - "3600"
    image: busybox
    name: busybox1
    volumeMounts:
    - name: busybox-dir
      mountPath: /etc/foo
  - command:
    - sleep 
    - "3600"
    image: busybox
    name: busybox2
    volumeMounts:
    - name: busybox-dir
      mountPath: /etc/foo
  volumes:
  - name: busybox-dir
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
