apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  activeDeadlineSeconds: 30
  template:
    metadata:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo hello; sleep 10;done
        image: busybox
        name: busybox-job
        resources: {}
      restartPolicy: Never
