apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: frontend

spec:
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.8
