apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2020-01-01T21:23:02Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "1578479"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/coredns
  uid: e45d4ef7-2cdc-11ea-a3d1-025000000001
secrets:
- name: coredns-token-g6qsd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"kubernetes.io/bootstrapping":"rbac-defaults"},"name":"system:coredns"},"rules":[{"apiGroups":[""],"resources":["endpoints","services","pods","namespaces"],"verbs":["list","watch"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get"]}]}
  creationTimestamp: "2020-01-01T21:23:02Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
  resourceVersion: "1578478"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Acoredns
  uid: e4611faa-2cdc-11ea-a3d1-025000000001
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
