apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  parallelism: 5
  completions: 15
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello; sleep 10; echo world
        image: busybox
        name: myjob
        resources: {}
      restartPolicy: OnFailure
status: {}
