apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - command: ["/bin/sh"]
    args: ["-c", "echo hello; sleep  3600"]
### Following is also correct ###
# - args:
#   - /bin/sh
#   - -c
#   - echo hello;sleep 3600
    image: busybox
    name: busybox1
  - command: ["/bin/sh"]
    args: ["-c", "echo hello; sleep  3600"]
### Following is also correct ###
# - args:
#   - /bin/sh
#   - -c
#   - echo hello;sleep 3600
    image: busybox
    name: busybox2
