apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: nginx
  type: NodePort

