apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
    name: wordpress
spec:
replicas: 2
  selector:
  matchLabels:
      run: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_PASSWORD
          value: secret:mysql-pass
        image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
